"""add middle_name phone birthdate to users

Revision ID: 8c7cfaf7938c
Revises: 3f13d040e13b
Create Date: 2026-02-26 16:36:06.004707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c7cfaf7938c'
down_revision = '3f13d040e13b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('middle_name', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('birthdate', sa.Date(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.drop_column('birthdate')
        batch_op.drop_column('phone')
        batch_op.drop_column('middle_name')

    # ### end Alembic commands ###
